const seed=[{"name": "Sefat Karim", "weekend": "Saturday", "phone": "01781597975", "joining": "01-01-2026"}, {"name": "Akram", "weekend": "Saturday", "phone": "01871976484", "joining": "08-03-2024"}, {"name": "Arman Alif", "weekend": "Saturday", "phone": "01406274628", "joining": "04-10-2025"}, {"name": "Sajedul Islam", "weekend": "Sunday", "phone": "01876608766", "joining": "13-12-2023"}, {"name": "Tarikul Islam", "weekend": "Sunday", "phone": "01401248381", "joining": "03-01-2026"}, {"name": "Tonmoy", "weekend": "Sunday", "phone": "01921080031", "joining": "02-11-2026"}, {"name": "Omar Faruk Majumder", "weekend": "Sunday", "phone": "01675562296", "joining": "31-12-2025"}, {"name": "Md Sujon", "weekend": "Monday", "phone": "01762946309", "joining": "12-07-2024"}, {"name": "Mosharof Hossain", "weekend": "Monday", "phone": "01927917924", "joining": "01-01-2026"}, {"name": "Md Raihan", "weekend": "Monday", "phone": "01931070660", "joining": "27-06-2026"}, {"name": "Moinul Islam", "weekend": "Tuesday", "phone": "01602871511", "joining": "05-01-2026"}, {"name": "Sifat Hossain", "weekend": "Tuesday", "phone": "01984382210", "joining": "24-06-2026"}, {"name": "Shakib Ahmed", "weekend": "Tuesday", "phone": "01321818169", "joining": "28-07-2026"}, {"name": "Al Arafat", "weekend": "Tuesday", "phone": "01327948737", "joining": "05-01-2026"}, {"name": "Kowshiq", "weekend": "Wednesday", "phone": "01956363216", "joining": "19-01-2024"}, {"name": "Mamun", "weekend": "Wednesday", "phone": "01518707855", "joining": "09-07-2025"}, {"name": "Sahil (Forever)", "weekend": "Wednesday", "phone": "01947127960", "joining": "28-06-2026"}, {"name": "Najmul Islam", "weekend": "Thursday", "phone": "01782417078", "joining": "17-05-2023"}, {"name": "Mehadi Hasan", "weekend": "Thursday", "phone": "01646406186", "joining": "22-10-2022"}, {"name": "Naim Khan", "weekend": "Thursday", "phone": "01615354665", "joining": "09-01-2025"}, {"name": "Rezaul Karim", "weekend": "Thursday", "phone": "01407722355", "joining": "01-12-2024"}, {"name": "Sami", "weekend": "Friday", "phone": "01407914895", "joining": "02-10-2024"}, {"name": "Sahil Sheikh", "weekend": "Friday", "phone": "01626429771", "joining": "05-01-2026"}, {"name": "Piyal Sarker", "weekend": "Friday", "phone": "01705952384", "joining": "04-01-2026"}, {"name": "Abu Torab", "weekend": "Friday", "phone": "01722639097", "joining": "28-06-2026"}];
let mods=JSON.parse(localStorage.getItem('smms_mods')||'null')||seed;
let leaves=JSON.parse(localStorage.getItem('smms_leaves')||'[]');
const days=['Sunday','Monday','Tuesday','Wednesday','Thursday','Friday','Saturday'];
function persist(){localStorage.setItem('smms_mods',JSON.stringify(mods));localStorage.setItem('smms_leaves',JSON.stringify(leaves))}
function show(id){document.querySelectorAll('.page').forEach(x=>x.classList.add('hidden'));document.getElementById(id).classList.remove('hidden');if(id==='dashboard')dash();if(id==='attendance')renderAttendance();if(id==='moderators')renderMods();if(id==='leave')renderLeaves()}
function isoLocal(d=new Date()){let z=d.getTimezoneOffset()*60000;return new Date(d-z).toISOString().slice(0,10)}
function dayOf(s){let [y,m,d]=s.split('-').map(Number);return days[new Date(y,m-1,d).getDay()]}
function activeLeave(name,date){return leaves.some(x=>x.name===name&&date>=x.start&&date<=x.end)}
function attKey(date){return 'smms_att_'+date}
function getAtt(date){return JSON.parse(localStorage.getItem(attKey(date))||'{}')}
function dash(){let date=isoLocal(), day=dayOf(date), a=getAtt(date);let off=mods.filter(x=>x.weekend===day), lv=mods.filter(x=>activeLeave(x.name,date));document.getElementById('total').textContent=mods.length;document.getElementById('off').textContent=off.length;document.getElementById('leaveCount').textContent=lv.length;document.getElementById('present').textContent=Object.values(a).filter(x=>x==='Present').length;document.getElementById('absent').textContent=Object.values(a).filter(x=>x==='Absent').length;document.getElementById('todayOff').innerHTML=off.length?off.map(x=>'<span class="badge">'+x.name+'</span>').join(' '):'No weekly off today.'}
function renderAttendance(){let date=document.getElementById('attDate').value||isoLocal();document.getElementById('attDate').value=date;let day=dayOf(date), saved=getAtt(date);document.getElementById('attBody').innerHTML=mods.map((x,i)=>{let auto=activeLeave(x.name,date)?'Leave':x.weekend===day?'Weekly Off':(saved[x.name]||'Present');return `<tr><td>${i+1}</td><td>${x.name}</td><td>${x.weekend}</td><td><select data-name="${x.name}" ${auto==='Weekly Off'?'disabled':''}><option ${auto==='Present'?'selected':''}>Present</option><option ${auto==='Absent'?'selected':''}>Absent</option><option ${auto==='Leave'?'selected':''}>Leave</option><option ${auto==='Weekly Off'?'selected':''}>Weekly Off</option></select></td></tr>`}).join('')}
function saveAttendance(){let date=document.getElementById('attDate').value,o={};document.querySelectorAll('#attBody select').forEach(s=>o[s.dataset.name]=s.value);localStorage.setItem(attKey(date),JSON.stringify(o));alert('Attendance saved successfully.');dash()}
function renderMods(){let q=(document.getElementById('search').value||'').toLowerCase();document.getElementById('modBody').innerHTML=mods.map((x,i)=>({x,i})).filter(o=>o.x.name.toLowerCase().includes(q)).map(o=>`<tr><td>${o.i+1}</td><td>${o.x.name}</td><td>${o.x.weekend}</td><td>${o.x.phone}</td><td>${o.x.joining}</td><td><button class="danger" onclick="delMod(${o.i})">Delete</button></td></tr>`).join('')}
function addMod(){let name=n.value.trim();if(!name)return alert('Enter name');mods.push({name,weekend:w.value,phone:p.value,joining:j.value});persist();n.value=p.value=j.value='';renderMods();fillLeave()}
function delMod(i){if(confirm('Delete this moderator?')){mods.splice(i,1);persist();renderMods();fillLeave();dash()}}
function fillLeave(){leaveMod.innerHTML=mods.map(x=>`<option>${x.name}</option>`).join('')}
function addLeave(){if(!leaveStart.value||!leaveEnd.value)return alert('Select dates');if(leaveEnd.value<leaveStart.value)return alert('End date cannot be before start date');leaves.push({name:leaveMod.value,start:leaveStart.value,end:leaveEnd.value,type:leaveType.value,reason:leaveReason.value});persist();leaveReason.value='';renderLeaves();dash()}
function renderLeaves(){fillLeave();leaveBody.innerHTML=leaves.map((x,i)=>`<tr><td>${x.name}</td><td>${x.start}</td><td>${x.end}</td><td>${x.type}</td><td>${x.reason||'-'}</td><td><button class="danger" onclick="delLeave(${i})">Delete</button></td></tr>`).join('')}
function delLeave(i){leaves.splice(i,1);persist();renderLeaves();dash()}
function report(){let m=reportMonth.value;if(!m)return;let rows=mods.map(x=>{let p=0,a=0,l=0,o=0;for(let k=1;k<=31;k++){let d=m+'-'+String(k).padStart(2,'0');if(d>m+'-31')continue;let dt=new Date(d+'T00:00:00');if(dt.getMonth()+1!==Number(m.slice(5)))continue;let st=activeLeave(x.name,d)?'Leave':x.weekend===dayOf(d)?'Weekly Off':getAtt(d)[x.name];if(st==='Present')p++;if(st==='Absent')a++;if(st==='Leave')l++;if(st==='Weekly Off')o++}return `<tr><td>${x.name}</td><td>${p}</td><td>${a}</td><td>${l}</td><td>${o}</td></tr>`}).join('');reportOut.innerHTML=`<div class="tableWrap"><table><thead><tr><th>Name</th><th>Present</th><th>Absent</th><th>Leave</th><th>Weekly Off</th></tr></thead><tbody>${rows}</tbody></table></div>`}
setInterval(()=>clock.textContent=new Date().toLocaleString(),1000);
attDate.value=isoLocal();reportMonth.value=isoLocal().slice(0,7);fillLeave();dash();
